image: node:16.15

stages:
  - create-env
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

.envs:
  stage: create-env
  script:
    - echo "ENV=$ENV" >> build.env
    - echo "SECRET_ID=$SECRET_ID" >> build.env
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
  artifacts:
    reports:
      dotenv: build.env

.build:
  stage: build
  script:
    - echo $ENV
    - npm install
    - apt-get update
    - apt-get install python3 -y
    - apt-get install python3-pip -y
    - apt-get install python3-setuptools -y
    - apt-get install groff -y
    - apt-get install less -y
    - pip3 install --upgrade pip
    - apt-get clean
    - npm --version
    - pip3 --no-cache-dir install --upgrade awscli
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - touch ~/.aws/config
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set aws_default_region "$AWS_DEFAULT_REGION"
    - aws configure list
  dependencies:
    - create-env
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm run test:fns
  only:
    - development

.deployment:
  stage: deploy
  script:
    - npm i -g aws-cdk
    - cdk --version
    - cdk bootstrap aws://$AWS_ID_ACCOUNT/$AWS_DEFAULT_REGION
    - cdk ls
    - npm run clean && cdk deploy --require-approval never
  artifacts:
    paths:
      - node_modules/

create-env:
  extends: .envs
  only:
    - development
  environment:
    name: development

build:
  extends: .build
  only:
    - development
  environment:
    name: development

deploy:
  extends: .deployment
  only:
    - development
  environment:
    name: development
